In [1]:
# Initial imports
import pandas as pd
from path import Path
from sklearn import tree
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [17]:
#  Import and read the nba data.
file_name = 'Resources/game_edited.csv'
df = pd.read_csv(file_name)
df

,TEAM_ID_HOME,FGM_HOME,FGA_HOME,FG_PCT_HOME,FG3M_HOME,FG3A_HOME,FG3_PCT_HOME,FTM_HOME,FTA_HOME,FT_PCT_HOME,...,PTS_OT4_AWAY,PTS_OT5_AWAY,PTS_OT6_AWAY,PTS_OT7_AWAY,PTS_OT8_AWAY,PTS_OT9_AWAY,PTS_OT10_AWAY,HOME_TEAM_WINS,HOME_TEAM_LOSSES,HOME_W
0,1610612744,41,96,0.427,9,30,0.300,20,22,0.909,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,1
1,1610612741,37,87,0.425,7,19,0.368,16,23,0.696,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,1.0,1
2,1610612737,37,82,0.451,8,27,0.296,12,15,0.800,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,1.0,0
3,1610612747,35,90,0.389,9,34,0.265,32,35,0.914,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0
4,1610612756,34,87,0.391,6,24,0.250,21,33,0.636,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4920,1610612749,43,100,0.430,15,46,0.326,15,21,0.714,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0
4921,1610612737,43,103,0.417,17,41,0.415,31,38,0.816,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0
4922,1610612743,39,87,0.448,10,33,0.303,11,17,0.647,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,1
4923,1610612766,41,78,0.526,8,29,0.276,24,27,0.889,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0
4924,1610612763,48,98,0.490,21,46,0.457,15,18,0.833,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,1

In [18]:
df.dropna()

,TEAM_ID_HOME,FGM_HOME,FGA_HOME,FG_PCT_HOME,FG3M_HOME,FG3A_HOME,FG3_PCT_HOME,FTM_HOME,FTA_HOME,FT_PCT_HOME,...,PTS_OT4_AWAY,PTS_OT5_AWAY,PTS_OT6_AWAY,PTS_OT7_AWAY,PTS_OT8_AWAY,PTS_OT9_AWAY,PTS_OT10_AWAY,HOME_TEAM_WINS,HOME_TEAM_LOSSES,HOME_W
0,1610612744,41,96,0.427,9,30,0.300,20,22,0.909,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,1
1,1610612741,37,87,0.425,7,19,0.368,16,23,0.696,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,1.0,1
2,1610612737,37,82,0.451,8,27,0.296,12,15,0.800,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,1.0,0
3,1610612747,35,90,0.389,9,34,0.265,32,35,0.914,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0
4,1610612756,34,87,0.391,6,24,0.250,21,33,0.636,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4920,1610612749,43,100,0.430,15,46,0.326,15,21,0.714,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0
4921,1610612737,43,103,0.417,17,41,0.415,31,38,0.816,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0
4922,1610612743,39,87,0.448,10,33,0.303,11,17,0.647,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,1
4923,1610612766,41,78,0.526,8,29,0.276,24,27,0.889,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0
4924,1610612763,48,98,0.490,21,46,0.457,15,18,0.833,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,1

In [19]:
#drop non-numerical data
drop_df = df.drop(columns=['HOME_W', 'TEAM_ID_HOME','TEAM_ID_AWAY','ATTENDANCE'], axis=1)
drop_df.head()

,FGM_HOME,FGA_HOME,FG_PCT_HOME,FG3M_HOME,FG3A_HOME,FG3_PCT_HOME,FTM_HOME,FTA_HOME,FT_PCT_HOME,OREB_HOME,...,PTS_OT3_AWAY,PTS_OT4_AWAY,PTS_OT5_AWAY,PTS_OT6_AWAY,PTS_OT7_AWAY,PTS_OT8_AWAY,PTS_OT9_AWAY,PTS_OT10_AWAY,HOME_TEAM_WINS,HOME_TEAM_LOSSES
0,41,96,0.427,9,30,0.300,20,22,0.909,21,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0
1,37,87,0.425,7,19,0.368,16,23,0.696,7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,1.0
2,37,82,0.451,8,27,0.296,12,15,0.800,7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,1.0
3,35,90,0.389,9,34,0.265,32,35,0.914,12,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0
4,34,87,0.391,6,24,0.250,21,33,0.636,13,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0

In [20]:
# split into features and target arrays
y = df['HOME_W'].values
X = drop_df.values

In [21]:
# Splitting into Train and Test sets into an 80/20 split.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78, train_size=0.80)

In [22]:
# Determine the shape of our training and testing sets.
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(3940, 86)
(985, 86)
(3940,)
(985,)

In [27]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [28]:
# Creating the decision tree classifier instance.
model = tree.DecisionTreeClassifier()
# Fitting the model.
model = model.fit(X_train_scaled, y_train)

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

In [ ]:
# create standard scalar instance
scaler = MinMaxScaler()

In [ ]:
#split preprocesed data into training/testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 3)

In [ ]:
#fit the standardscaler
X_scaler = scaler.fit(X_train)

In [ ]:
#scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [ ]:
# # define the model
# number_input_features = len(X_train[0])
# hidden_nodes_layer1 = 100
# hidden_nodes_layer2 = 60
# hidden_nodes_layer3 = 5

# nn = tf.keras.models.Sequential()

# #first hidden layer
# nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# # Second hidden layer
# nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# # Third hidden layer
# nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="sigmoid"))

# #output layer
# nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# #check structure
# nn.summary()

In [ ]:
# # Compile the model
# nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
# # Train the model
# fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

In [ ]:
# # Evaluate the model using the test data
# model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
# print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

In [ ]:
from imblearn.combine import SMOTEENN
smote_enn = SMOTEENN(random_state=0)
X_resampled, y_resampled = smote_enn.fit_resample(X, y)

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

In [ ]:
from sklearn.metrics import confusion_matrix
y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)

In [ ]:
from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_test, y_pred)

In [ ]:
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))